### PR TITLE
Fix long dropdown when fetch balances

### LINKED ISSUE #47: Fix long dropdown issue
Screen Shot 2022-07-21 at 16 46 06

### PR DESCRIPTION
**Pull request by ken-futureverse**
## Summary

Closes #47

### CODE REVIEW

File: src/views/AccountDetailNew/index.vue [hunk 1]
```diff
@@ -447,7 +447,11 @@ export default {
           if (res === undefined || typeof res !== "object") {
             return Promise.reject();
           }
-          this.tokenDetails = res.balances;
+          this.tokenDetails = res.balances.filter(token => {
+            const {free, assetId} = token;
+            return Number(free) > 0 || (assetId === 1 || assetId === 16000);
```
Comment (KarishmaBothara) [inline src/views/AccountDetailNew/index.vue:452]: was thinking, if we could query staking asset and use that.. instead of (assetId === 1 || assetId === 16000)..
But it is used as this twice in this file.. so I think its fine

**Review by KarishmaBothara — APPROVED** [review]

File: src/views/AccountDetailNew/index.vue (hunk 1 above)
Comment (ken-futureverse) [reply src/views/AccountDetailNew/index.vue:452]: yeah, fair point, I'm cutting corners here a bit, plus trying to minimise the code changes.
